### ISSUE TITLE
feature request: send message to OTHER_IRC_CHANNELS?

### ISSUE THREAD

**Issue by plowsof** [cfindlayisme/wmb#17]
no experience with go sadly but people may want to broadcast a message to multiple channels. Is this a valid feature request?

if env variable `BROADCAST` == true and `OTHER_IRC_CHANNELS` then do it.

for now i just added a blind loop to the http.go, and only use the other channels env variable.

```go
	for _, channel := range env.GetOtherChannels() {
		err := ircclient.SendMessage(ircclient.IrcConnection, channel, ircclient.FormatMessage(msg))
		if err != nil {
			c.String(http.StatusInternalServerError, "Failed to send message to IRC server")
		}
		c.String(http.StatusOK, "Message sent")
	}
```

**Comment by cfindlayisme** [comment]
Yeah actually - I was planning on adjusting how /directedMessage works which I think would work for your use case.

Ie, currently the struct is
```
type DirectedIncomingMessage struct {
	Target          string
	IncomingMessage IncomingMessage
}
```

Which currently looks like this for the payload you'd send:
```
{
  "Target": "#exampleTarget",
  "IncomingMessage": {
    "Message": "Hello, world!",
    "Password": "examplePassword",
    "ColourCode": 3
  }
}
```

I'd also like to accommodate Target being an array vs just a single string, so that we can in one JSON payload send a message to multiple targets (ie channels, users.) So it would look like this:
```
{
  "Target": ["#exampleTarget1", "#exampleTarget2"],
  "IncomingMessage": {
    "Message": "Hello, world!",
    "Password": "examplePassword",
    "ColourCode": 3
  }
}
```
Currently, you could just hit /directedMessage with this payload a couple times per target channel
```
{
  "Target": "#exampleTarget",
  "IncomingMessage": {
    "Message": "Hello, world!",
    "Password": "examplePassword",
    "ColourCode": 3
  }
}
```
To achieve what you want without having to modify the code. I'm going to try adding the code in such a way you can do this or the array, and it'll accept either without complaint.

I really need to do up better documentation for the endpoints registered in main.go (ie, subscription) but only recently started getting in my flow, so I'll see if I can implement this over the next week or so (finally got a chunk of unit testing written after so much delaying)

**Comment by cfindlayisme** [comment]
README needs an update now, but try
```
{
    "Message": "Hello, World!",
    "Password": "password",
    "ColourCode": null,
    "Broadcast": true
}
```

Still going to adjust directedMessage as stated above, but this was a quick win. Broadcast and ColourCode are both optional. If omitted or set to null things will still work.

# PS
I also broke password auth a few commits ago somehow - if you're using this in a prod environment please update asap. I added a unit test to check for this so I don't do it again by mistake.

I also forgot to create the table for the DB in the opening of the database for subscriptions, so also a problem there I resolved and wrote a test for to prevent again too. It'll panic and re-connect each time someone says something in the channel if you've got the bad release.

**Comment by cfindlayisme** [comment]
There. Feature should be added and I've added tests and fixed a few bugs on the way. I'll let you try it out before I close this, but off to write tests for the rest of the code now so I can stop breaking things!

**Comment by plowsof** [comment]
thank you for the prompt reply and detailed alternatives. Target being an array would be a very clean and useful solution for directedMessage. Seems like you are back in your flow, awesome work. Will report back when im using the new version

**Comment by plowsof** [comment]
works perfect :+1: :star:
